Logging Added to Preferences
NetLogo/NetLogo pull request #1855
Opened 2020-09-03 20:19 UTC by Loafie

Changes made to add logging to the settings panel and change the directory where log files are stored.

2020-09-03 20:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetLogo/NetLogo?pullRequest=1855) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetLogo/NetLogo?pullRequest=1855) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetLogo/NetLogo?pullRequest=1855) it.</sub>

2020-09-04 14:12 UTC, LaCuneta requested changes
Overall this looks good, a couple small issues I left comments on in the code.  The rebase to hexy didn't quite work as a merge commit got added, but that's fine as I can squash this when I merge it in, or if you want you can try to get your commits re-applied without the merge commit.

There are some other updates for logging I thought of while reviewing this, but I'll handle those separately.

2020-09-04 20:05 UTC, Loafie commented on netlogo-gui/project/autogen/i18n/GUI_Strings_en.txt
> +tools.preferences.loggingEnabled = Logging Enabled:
Done

2020-09-04 20:05 UTC, Loafie commented on netlogo-gui/src/main/app/App.scala
> +import java.util.prefs.{ Preferences => JavaPreferences }
Done

2020-09-04 20:05 UTC, Loafie commented on netlogo-gui/src/main/app/App.scala
> +    if (loggingConfigPath != null || prefs.get("loggingEnabled", "false").toBoolean ){
Done

2020-09-04 20:13 UTC, LaCuneta commented
@Loafie Is this ready for re-review?  Can you sign the CLA as well (it's showing unsigned)?

2020-09-04 20:17 UTC, Loafie commented
Ready for re-review.

2020-09-08 15:24 UTC, LaCuneta approved these changes

2020-09-08 15:25 UTC, merged