Add try catch to show an error message when an IOException occurs while using BehaviourSpace.
NetLogo/NetLogo pull request #1902
Opened 2021-02-07 19:22 UTC by Wolgo

Essentially this changes the error message from:

![image](https://user-images.githubusercontent.com/15855950/107157016-0544ec00-6982-11eb-9cc0-97eb207f8630.png)

to:

![image](https://user-images.githubusercontent.com/15855950/107156596-88b10e00-697f-11eb-93a8-6e236b5e763e.png)

This is related to issue #243
I have no idea what the impact would be on Mac or Linux. But for windows, it seems to work. If Mac and Linux give any IOException it should come in a nice little window now instead of an error that asks you to report it.

2021-02-07 19:47 UTC, qiemem commented
Are you sure it keeps outputting after the exception is thrown? An error is much preferred to silently dropping data. Indeed, that error means that netlogo can't continue to write to the file while it's open in another program. It seems like the real fix is to lock the file on windows while it runs (though I don't know anything about windows).

2021-02-07 20:23 UTC, Wolgo commented
I'm not entirely sure what you mean. Both before and after my change the behaviour space aborts the experiment (and thus never starts outputting). The difference is that instead of showing the first picture, which tells you that you should report this problem on GitHub, we show you an error that only tells you that the file can't be used because it is already open, which the user can fix by closing the file.

This mostly addresses when the file is open in Excel before we start the experiment. (And thus we can't get a lock, because it already is locked by Excel.) A quick test on my end shows that we already lock the file.

2021-02-07 21:17 UTC, qiemem commented
Ah! My apologies. I misread your commit message. Thanks for clarifying the lock file situation as well.

2021-02-22 18:44 UTC, LaCuneta requested changes
Thank you for your contribution!  I found mostly small code style issues in the PR, I left comments for those.  One additional change I'd request, since you're adding the `java.io.IOException` import, it'd be good to remove the fully-qualified reference on line 174, so `case ex: java.io.IOException =>` can just be `case ex: IOException =>`.  Once those items are resolved I think we can merge.

Let me know if you have questions on anything.

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +import java.io.{IOException}
We've switched to adding a space after the `{` and before the `}`, so `import java.io.{ IOException }`.  Also, prefer to move this above the internal `org.nlogo` imports, but below the package statement.

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +	    addExporter(new SpreadsheetExporter(
We use two spaces, never tabs for indentation.  Here and a couple other spots used tabs.

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
>          worker.protocol,
Make sure these statements are indented one level in from the `addExporter` start.

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +      try{
Prefer a space before the `{`

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +	  catch{
Prefer a space before the `{`

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +      }
Make sure this closing brace is indented to the same level as the `try/catch` statements.

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +		case e: IOException => failure(e); return
I think I see why the `; return` is here as this is copied from above.  If you're going to split things onto separate lines I'd prefer to drop the `;` and have the `failure(e)` and `return` on their own lines.  You could also do things are they are above in this file and keep it all on a single line, `catch { case e: IOException => failure(e); return }`

2021-02-22 18:44 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +      }
Similar comments here as above, make sure indentation uses spaces, make sure things are properly aligned, and either split the catch block up or move it to one line.

2021-02-22 18:45 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/Supervisor.scala
> +import java.io.{IOException}
I should add, I know the other imports don't exactly match this style as they are older.  I'll leave it to you if you want to correct them, but we do add the spaces in new code.

2021-04-15 16:07 UTC, LaCuneta commented
I went ahead and made the changes and did a little more cleanup:  https://github.com/NetLogo/NetLogo/commit/8232012794418cf48f07a001a659a55696d7a710

2021-04-15 16:07 UTC, closed without merging