make separate CodeTab window appear to right or left of NetLogo App
NetLogo/NetLogo pull request #1925
Opened 2021-06-17 12:11 UTC by brandesNW

fixes #1907

2021-06-17 13:09 UTC, LaCuneta requested changes
Thanks for this!  The code mostly looks good to me, I'm glad it was a pretty small fix.  I tested on Linux and noticed a few oddities:

1. (With single monitor) If I maximize the NetLogo window and then pop out the code window, it (usually, see item 3) still goes behind the main NetLogo window and I have to move windows around to get it on top.
2. (With dual monitors - left/right) If I maximize the NetLogo window on the left monitor and pop out the code window, it goes to the right monitor.  That's not the biggest problem, it's just a little weird.  If I maximize the NetLogo window on the right monitor and pop out the code window, I get the same behavior as the single monitor above.
3. In many cases (but not all, and I can't figure why), when I pop out the code tab window it does not have focus for me to start typing code, even if it is in view.  I would expect to be able to just start typing after popping it out, no matter where the window shows up.

I think item 3 is really the most serious one to me.  Even if the windows are overlapping after I click the pop out button, I at least want to be able to see the code window and start typing code or moving it around.

Let me know if you have any questions.

2021-06-17 22:13 UTC, brandesNW commented on netlogo-gui/src/main/app/CodeTabContainer.scala
> +                       horizontalSpacing: Int = 10) extends JFrame with LinkChild {
I wanted to expose them for future use. For example we might allow them to be created by a config file. 
I could just set them as local variables if you prefer.

2021-06-18 12:51 UTC, LaCuneta commented on netlogo-gui/src/main/app/CodeTabContainer.scala
> +                       horizontalSpacing: Int = 10) extends JFrame with LinkChild {
Leaving them in is fine, I just wanted to make sure the change was intentional.

2021-06-29 20:46 UTC, LaCuneta requested changes
The behavior was much better, I was able to type code every time and way I popped out the code tab window, and it never popped behind the main NetLogo window.

I noticed a few whitespace issues I left comments on.  Once those are fixed this should be good to merge.

2021-06-29 20:46 UTC, LaCuneta commented on netlogo-gui/src/main/app/CodeTabsPanel.scala
> +
I'm not sure the blank space after the `new Runnable() {` is helpful here, I'd prefer it be between the end of the method above and the `java.awt.EventQueue` line.

2021-06-29 20:46 UTC, LaCuneta commented on netlogo-gui/src/main/app/CodeTabsPanel.scala
> +})
The spacing here looks to be at 4 spaces, not 2.  The closing `})` is mis-aligned and should be indented 2 spaces to match up with the `(new Runnable() {` opening level.

2021-06-30 12:29 UTC, LaCuneta approved these changes

2021-06-30 12:31 UTC, merged