extract-rgb
NetLogo/NetLogo pull request #1934
Opened 2021-07-16 18:28 UTC by IsaacNoel

Updated the extract-rib primitive to accept more types of input

2021-07-16 18:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetLogo/NetLogo?pullRequest=1934) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetLogo/NetLogo?pullRequest=1934) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetLogo/NetLogo?pullRequest=1934) it.</sub>

2021-07-19 14:33 UTC, brandesNW commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> -
Keep the blank line.

2021-07-19 14:58 UTC, brandesNW requested changes
Isaac, great job finding and making changes in all the relevant files.
There are some minor change requests. The one substantive one is that 
> extract-rgb  [215 50 41 100]
shouled be  [215 50 41], not  [215 50 41 100]

2021-07-19 14:58 UTC, brandesNW commented on netlogo-headless/src/main/prim/etc/_extractrgb.java
> -
Keep the blank line.

2021-07-19 14:58 UTC, brandesNW commented on netlogo-headless/src/main/prim/etc/_extractrgb.java
> +        throw new org.nlogo.nvm.RuntimePrimitiveException(context, this, "Color must be a number or a valid RGB List.");
valid RGB(A) List

2021-07-19 14:58 UTC, brandesNW commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +      return rgb;
This should return only the first 3 elements of rgb. Alpha should not be included. The test also needs to be updated.

2021-07-19 14:58 UTC, brandesNW commented on netlogo-headless/src/main/prim/etc/_extractrgb.java
> +      return rgb;
This should return only the first 3 elements of rgb. Alpha should not be included. The test also needs to be updated.

2021-07-19 14:58 UTC, brandesNW commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +        throw new org.nlogo.nvm.RuntimePrimitiveException(context, this, "Color must be a number or a valid RGB List.");
valid RGB(A) List

2021-07-19 17:47 UTC, brandesNW approved these changes

2021-07-20 13:57 UTC, LaCuneta requested changes
Thanks for your work on this!  Nice job tracking down all the required update locations.  Having the positive/negative language tests is also much appreciated.

My usual proviso when doing a PR review that works with old code in NetLogo or one of its extensions:  I'll be applying our [current style guide](https://github.com/NetLogo/NetLogo/wiki/Code-formatting) and coding standards.  You may see older code in the same or nearby file(s) that doesn't fit these standards, but our policy is all new and updated code going in should be at our currently expected quality.  It'll mostly be small, easily corrected stuff.

I see you did a `try`/`catch` around getting a `double` value and fell back to trying to get a `LogoList`.  My preference would be to just explicitly do the type check instead of relying on exceptions in what is not really an exceptional circumstance (user sent a list value). Something like this should work:

```java
    Object val = args[0].report(context);
    if (val instanceof Double) {
      Double d = (Double)val;
      // do double stuff...
    } else if (val instanceof LogoList) {
      LogoList rgb = (LogoList)val;
      // do list stuff...
    } else {
      // throw...
    }
```

You might wind up throwing exceptions in a couple of places, but if it's internationalized (see comments), that shouldn't be too big a deal.

I only left review comments on the GUI version, but updates would be needed in the headless version, too.  Let me know if you have any questions.

2021-07-20 13:57 UTC, LaCuneta commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +import org.nlogo.core.SyntaxJ;
I don't see this `SyntaxJ` import used anywhere.  Can it be removed?  Actually, I think `Syntax` above it could be, too, if you wanted.

2021-07-20 13:57 UTC, LaCuneta commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +    try{
Prefer space after keyword and before opening curly bracket.  There are other occurrences of this, but I'll just leave this comment.

2021-07-20 13:57 UTC, LaCuneta commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +    catch(LogoException l){
Prefer spaces after opening bracket before opening paren and after closing paren and before opening curly bracket.  There are other occurrences of this, but I'll just leave this comment.

2021-07-20 13:57 UTC, LaCuneta commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +      org.nlogo.api.Exceptions.ignore( l ) ;
Prefer no spaces around method arguments or before closing semicolon.

2021-07-20 13:57 UTC, LaCuneta commented on netlogo-gui/src/main/prim/etc/_extractrgb.java
> +        throw new org.nlogo.nvm.RuntimePrimitiveException(context, this, "Color must be a number or a valid RGB(A) List.");
Move the error message into the internationalization files, so they can be internationalized at some future point.  There are [two](https://github.com/NetLogo/NetLogo/blob/hexy/shared/i18n/Errors_en.txt) [spots](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/project/autogen/i18n/Errors_en.txt) for this, oddly.  You can see they organize their "access strings" by prim package and name.  [Here is a sample usage](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/prim/etc/_sublist.java#L23-L24).

Change the error message to be a little more helpful, something like "...number or a valid RGB(A) list with 3 or 4 number items with values from 0 to 255." to be explicit about what an "RGB(A) list" actually is.

2021-07-22 13:33 UTC, LaCuneta requested changes
Thanks for the I18N changes and other style work!  

I should've been clearer about one style point - we prefer spaces after statement keywords and before opening parens, so `if (..) {}`, `catch (..) {}`, and `for (..) {}`.  Once those changes are made, let me know and I think we can merge this.

2021-07-22 14:00 UTC, SethTisue commented
> the extract-rib primitive

So the LORD God caused the man to fall into a deep sleep, and while he slept, He took one of the man’s ribs and closed up the area with flesh. And from the rib that the LORD God had taken from the man, He made a woman and brought her to him.

2021-07-22 15:35 UTC, LaCuneta approved these changes

2021-07-22 15:36 UTC, merged