Fixes #1906
NetLogo/NetLogo pull request #1942
Opened 2021-08-18 19:10 UTC by brandesNW

Make sure Tools-> Hide Command Center and Edit-> Undo menu items
appear appropriately.
Don't revoke or offer Actions in CodeTabsPanel.scala.
Eliminate unnecessary tab switching with InterfaceTab.
Set current tab when the new tab is already selected.

2021-08-18 19:26 UTC, brandesNW commented
I tested with all the combinations of opening and closing the separate code tab on my MacOs system.
**Open a separate Code tab**

-  Click Code tab checkbox on
- Control-click with the mouse on the tab bar of the Code tab
- Command + Shift + W on Mac, Control + Shift + W on other operating systems

**Return a separated Code tab to the main NetLogo window** 
-  Click the window’s close button
-  Click Code tab checkbox on
- Control-click with the mouse on the tab bar of the Code tab
- Command + W on Mac, Control + W on other operating systems

Note: before the fix moving between the Info tab and a separated Code tab sometimes produced multiple Edit->Undo and Redo menus.

**Move between the tabs**

- Click the tab
- Use shortcuts, as shown in the Tabs Menu
- Choose options from the Tabs Menu

2021-08-18 19:42 UTC, LaCuneta requested changes
Thanks for looking into this.

- Please re-word your commit message to start with a short description of the change and not the `"Fixes #1906"` text.  You can include the `"Fixes #1906"` in the first line if it's less than 72 characters, otherwise put it on a separate line in the body.
- Make sure you have a blank line between the first line "header" of your commit message and any extra "body" text.  GitHub formats the continuous lines okay, but git has trouble.
- Make sure pull request titles also indicate what the issue/change instead of just referencing an issue number.

Functionality issues:

Scenario 1: Open NetLogo, pop out the code tab (using the checkbox if it matters) and make sure the interface tab is selected and visible.  Click in the code area, type `Ctrl+/`.  The command center is hidden, but a `/` is also type in the code window.  If a command hotkey is triggered, I would expect no `/` to be added to the code area.

Also with this scenario `Ctrl+Shift+C` does not bring me to the command center from the code area.  That isn't the biggest deal, but it is a little weird for one of those hotkeys to work and the other to not.

Scenario 2: Open NetLogo, pop out the code tab (using the checkbox).  Then click on the Info tab in the main window.  Note that the command center menu items are still in the tools menu but neither of them does anything.  I'd expect them to be hidden or disabled if they are of no use on the current tab.  Note that they are hidden as expected if the code tab is docked (as they were in NetLogo versions prior to the pop-out code tab).  

Then with the Info tab still selected, close the code tab window, then click on the interface tab, then check the Tools menu and there are duplicates of the command center hotkeys.

Let me know if you have questions on anything.

2021-08-18 21:04 UTC, brandesNW commented
R.e. Scenario 1: Open NetLogo, pop out the code tab (using the checkbox if it matters) and make sure the interface tab is selected and visible try CMD+/  and Ctrl+Shift+C
I tested this on my MacOS system
When in the code tab, with the interface tab visible, no command hotkey is triggered for CMD+/ or Ctrl+Shift+C, nothing is typed in the code text area.
When in the interface tab, with the separate code tab visible both hotkeys work as expected.

I  think this should be the expected behavior.

2021-08-18 21:11 UTC, brandesNW commented
These are not reproducible on my MacOS system

Scenario 2: Open NetLogo, pop out the code tab (using the checkbox). Then click on the Info tab in the main window.
On my MacOS system neither the Hide or Jump commands appears in the menu, as expected.

Then with the Info tab still selected, close the code tab window, then click on the interface tab, then check the Tools menu.  A single copy of the Hide and Jump commands is in the Tools menu

2021-08-31 17:49 UTC, LaCuneta approved these changes
Confirmed all test scenarios worked as expected (except the Ctrl-/ in the code tab, but that's less critical).

2021-08-31 17:49 UTC, merged