BehaviorSpace Import/Export Experiments + Naming Requirements
NetLogo/NetLogo pull request #2132
Opened 2023-07-31 21:26 UTC by ERSUCC

### Motivation

Currently, NetLogo has no functionality for importing and exporting individual BehaviorSpace experiments, but there is functionality for running individual experiments headlessly. To use this feature, you have to manually extract and format the desired experiments from the text version of your saved NetLogo model file. Having the ability to import and export experiments would make this easier, and it would make it easier to transfer individual experiments between models or devices.

### GUI Changes

In the initial BehaviorSpace window, there are now import and export buttons. You can import any number of experiments at once and at any time while the window is open. The export button is grayed out until one or more experiments have been added, at which point you can select any number of experiments to export them at the same time. Each experiment will be saved to its own file, named according to the name of the experiment in the GUI.

### Other Changes

Currently, you can name all of your experiments with the exact same name. If you were to export them all using the new export functionality, it would overwrite the same file over and over and you would end up with only one exported experiment. To prevent this, I added a new requirement that all experiments within a model have unique names. To ensure that importing goes smoothly with this new requirement, I also added code to automatically rename imported experiments if there are naming conflicts with the existing experiments in that model. For example, if you have an experiment named "experiment" and you try to import an experiment also named "experiment", the imported experiment will be renamed to "experiment-1".

You can also currently name experiments with an empty string, which would also cause issues with exporting experiments, so I added a requirement that experiments have non-empty names.

The documentation was also changed to reflect the new changes in the GUI and the new requirements for naming.

2023-07-31 22:07 UTC, ERSUCC commented
Just found a really important bug, don't run the tests yet!

2023-08-01 15:33 UTC, brandesNW commented
The directory choosing should be improved, and the user should be able to choose the the name of the output file. When I ran the code the dialog opened in my home directory, but I couldn't create the file there.  I think the dialog should be similar to that for tables and spreadsheets where the user is given a default name, but can browse for a directory, and create a new one if they want.

2023-08-07 14:11 UTC, brandesNW requested changes
Good job. Please address the above issues.

2023-08-07 14:11 UTC, brandesNW requested changes
Good job. Please address the above issues.

2023-08-08 21:13 UTC, brandesNW approved these changes
no more changes requested

2023-08-09 14:52 UTC, LaCuneta requested changes
Nice work!  I tested out a bunch of variations and everything seems good.  I left a few very small items in the comments.

The only thing that seemed off to me was that when exporting a single experiment the model title wasn't included.  If you already discussed and decided on that for a reason, that's fine.  To me I'd prefer having my model title prepended (as when doing the multi-export) as it helps me keep track of where the experiment came from.

2023-08-09 14:52 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/ProtocolEditable.scala
> +    for (exp <- experimentNames) {
I'd probably just do `if (experimentNames.contains(name.trim)) ...` here for clarity.

2023-08-09 14:52 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/ManagerDialog.scala
> +          for (protocol <- new LabLoader(manager.workspace.compiler.utilities, true, manager.protocols.map(_.name).to[collection.mutable.Set])(scala.io.Source.fromFile(file).mkString))
Nit: Break up line to stay under 120 columns.

2023-08-09 14:52 UTC, LaCuneta commented on netlogo-gui/src/main/lab/gui/ManagerDialog.scala
> +              javax.swing.JOptionPane.showMessageDialog(manager.workspace.getFrame, s"""Invalid format in "${file.getName}".""", "Invalid", javax.swing.JOptionPane.ERROR_MESSAGE)
Nit: Break up line to stay under 120 columns.

2023-08-09 14:52 UTC, LaCuneta commented on autogen/docs/behaviorspace.md.mustache
> +run headlessly.
Maybe point out the experiment XML can be hand-edited in a text editor or edited in another script/language for running headlessly as another benefit here.

2023-08-09 18:49 UTC, LaCuneta approved these changes

2023-08-09 18:50 UTC, merged