BehaviorSpace List Expansion Output
NetLogo/NetLogo pull request #2145
Opened 2023-08-25 17:00 UTC by ERSUCC

### Motivation

Reporters that return a list currently have all elements of each list combined into one cell in both the spreadsheet and table output formats, which makes parsing more difficult. The list expansion output serves as a supplementary output, displaying expanded versions of all list reporters with a single value in each cell.

### GUI Changes

The run options dialog now has an additional file select input after the existing inputs for spreadsheet and table output, which is used to select the output file location for the list expansion output. It must be selected in tandem with one or both of the existing output formats, because the expanded lists are extracted from the existing output rather than the data being collected separately during the experiment, which was done to conserve memory.

### New Format

The list expansion format contains all expanded lists, ordered first by run, then by reporter name, then by tick. Each line contains the reporter name, the run number, the parameter values specified for that run, the tick number, and all the list elements.

### Other Changes

The documentation was changed to include details about the new output format, and a sample image was added to match the sample images used for the existing output formats in the documentation.

### Note: reasonably large changes will need to be made once the pause/resume pull request has been integrated.

2023-08-28 22:34 UTC, brandesNW requested changes

2023-08-28 22:34 UTC, brandesNW commented on autogen/docs/behaviorspace.md.mustache
> +according to the setting of **Measure runs at every step** option. For **Table output** and
Adjust for new wording and reporter option for "Run metrics", which replaces **Measure runs at every step**

2023-08-30 17:38 UTC, brandesNW commented
the --lists option didn't produce any output for me. In sbt I ran

2023-08-30 22:34 UTC, brandesNW commented
Ready for Jeremy's review

2023-09-01 17:04 UTC, LaCuneta approved these changes
Okay, looks good to me, thank you for your work on this.  We'll think about any needed UI changes to clarify the output options later.

2023-09-01 17:04 UTC, merged