BehaviorSpace exporter version number
NetLogo/NetLogo pull request #2150
Opened 2023-09-07 21:42 UTC by ryanp8

**Motivation**
Because there have been many changes to the format of the spreadsheet exporter which is used to generate lists, stats, and potentially plots in the future, it will be useful to keep track of the version of the spreadsheet. This allows older versions that cannot generate the new results through the post processors to be easily identified. While version numbers for lists, stats, and table are not necessary, they are added for consistency and future-proofing.

**Changes**
When a csv file is generated by a table, spreadsheet, lists, or stats exporter, the first row now has an additional column that has the type of exporter followed by `version 2.0`. For example, a table would say `Table version 2.0`.

Changes to existing tests are not needed because the tests omit the file header.

2023-09-08 15:35 UTC, brandesNW commented
There are tests that fail because of the header change and need to be updated

For example:

> [info] - successful run *** FAILED ***
> [info]   Expected "...sults (NetLogo 6.3)"[]
> [info]   "models/test/lab/Fi...", but got "...sults (NetLogo 6.3)"[,"Table version 2.0"]
> [info]   "models/test/lab/Fi..." (TestMain.scala:98)
> [info]   org.scalatest.exceptions.TestFailedException:

you can locate more by searching the results pages for "failed"

https://github.com/NetLogo/NetLogo/actions/runs/6115052606/job/16598123177?pr=2150
https://github.com/NetLogo/NetLogo/actions/runs/6115052606/job/16598123489?pr=2150

2023-09-08 15:37 UTC, brandesNW commented
The image files also need to be updated in the documentation.

2023-09-08 21:27 UTC, brandesNW approved these changes
Thanks for this update.
This depends on PR 2146 - BehaviorSpace Statistics Exporter

2023-09-11 22:00 UTC, brandesNW commented
All output files now have a second column in the first row "Table Version 2.0" etc.
This is in the doc, and all have NetLogo 4.0 and a recent date.

2023-09-12 14:59 UTC, LaCuneta requested changes
Thanks for this!  Just a couple very small items in the comments.

2023-09-12 14:59 UTC, LaCuneta commented on netlogo-core/src/main/api/LabExporterType.scala
> +}
Nit: Prefer blank lines at end of files.

2023-09-12 14:59 UTC, LaCuneta commented on netlogo-core/src/main/api/LabExporterVersion.scala
> +}
Nit: Prefer blank lines at end of files.

2023-09-12 16:37 UTC, merged