BehaviorSpace Sub Experiment Bug Fixes
NetLogo/NetLogo pull request #2156
Opened 2023-09-11 17:43 UTC by ERSUCC

Removed accidental debug statement and fixed issue with constant redefine checking

2023-09-12 16:47 UTC, brandesNW commented
The previous examples meet expectations. However the following should produce a constant redefined error.

```
["a" [1 3 5]]
["a" 33]
[["b" [6 1 9]]]
```

gives

```
[run number]	a	b	[step]
1	1	6	1
2	1	7	1
3	1	8	1
4	1	9	1
5	4	6	1
6	4	7	1
7	4	8	1
8	4	9	1
```

the line `["a" 33] `seems to just be ignored.

2023-09-12 22:11 UTC, brandesNW commented
There are places in the files
netlogo-gui/resources/i18n/GUI_Strings_en.properties
netlogo-gui/src/main/lab/gui/ProtocolEditable.scala
that need to be reconciled with hexy
If you get all of them the conflicts may go away.

2023-09-12 22:16 UTC, brandesNW requested changes

2023-09-12 22:16 UTC, brandesNW commented on netlogo-gui/resources/i18n/GUI_Strings_en.properties
> +edit.behaviorSpace.list.increment = Increment list "{0}" exceeds the number of possible runs
take value from hexy

2023-09-12 22:16 UTC, brandesNW commented on netlogo-gui/src/main/lab/gui/ProtocolEditable.scala
> +              complain(I18N.gui.get("edit.behaviorSpace.invalidFormat")); return None
take value from hexy

2023-09-12 22:22 UTC, brandesNW commented
my testing was successful

2023-09-13 12:55 UTC, brandesNW commented
The netlogo-gui/resources/i18n/GUI_Strings_en.properties change is good.
Isaac and Ryan don't get a conflict when they view it (because of their repo?)
Maybe it can't be rebased because of the order in which things were integrated.

2023-09-13 12:55 UTC, brandesNW approved these changes

2023-09-13 18:21 UTC, ERSUCC commented
Issue with error messages resolved. Let me know if it is better now.

2023-09-13 20:10 UTC, LaCuneta approved these changes
LGTM :+1:

2023-09-13 20:10 UTC, merged